// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_shop_backend_esense.Data;

#nullable disable

namespace e_shop_backend_esense.Migrations
{
    [DbContext(typeof(EShopDbContext))]
    [Migration("20230204142234_seed_cars")]
    partial class seed_cars
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("e_shop_backend_esense.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cars"
                        },
                        new
                        {
                            Id = 11,
                            Name = "BMW",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Honda",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Toyouta",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 23,
                            Name = "Lexus",
                            ParentCategoryId = 13
                        },
                        new
                        {
                            Id = 14,
                            Name = "Mercedes",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 24,
                            Name = "Maybach",
                            ParentCategoryId = 14
                        },
                        new
                        {
                            Id = 25,
                            Name = "Benz",
                            ParentCategoryId = 14
                        },
                        new
                        {
                            Id = 26,
                            Name = "AMG",
                            ParentCategoryId = 14
                        },
                        new
                        {
                            Id = 2,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Laptops",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 27,
                            Name = "HP",
                            ParentCategoryId = 15
                        },
                        new
                        {
                            Id = 28,
                            Name = "Acer",
                            ParentCategoryId = 15
                        },
                        new
                        {
                            Id = 29,
                            Name = "Dell",
                            ParentCategoryId = 15
                        },
                        new
                        {
                            Id = 17,
                            Name = "Monitors",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 30,
                            Name = "LG",
                            ParentCategoryId = 17
                        },
                        new
                        {
                            Id = 31,
                            Name = "Samsung",
                            ParentCategoryId = 17
                        },
                        new
                        {
                            Id = 16,
                            Name = "PC",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phones"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Apple",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 22,
                            Name = "Huawei",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Clouthes"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Men",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 19,
                            Name = "Women",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 20,
                            Name = "Kid",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Books Sub-Category 1",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 7,
                            Name = "Books Sub-Category 2",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 8,
                            Name = "Category 3"
                        });
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStuck")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Rate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 11,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "BMW 0",
                            OldPrice = -500m,
                            Price = 9030m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 10,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 11,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "BMW 1",
                            OldPrice = -500m,
                            Price = 5308m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 18,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 11,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "BMW 2",
                            OldPrice = -500m,
                            Price = 7514m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 26,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 11,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "BMW 3",
                            OldPrice = -500m,
                            Price = 5262m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 34,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 11,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "BMW 4",
                            OldPrice = -500m,
                            Price = 7439m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 42,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 11,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "BMW 5",
                            OldPrice = -500m,
                            Price = 9175m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 50,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 11,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "BMW 6",
                            OldPrice = -500m,
                            Price = 9339m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 58,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 11,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "BMW 7",
                            OldPrice = -500m,
                            Price = 9789m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 66,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 11,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "BMW 8",
                            OldPrice = -500m,
                            Price = 6171m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 74,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 11,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "BMW 9",
                            OldPrice = -500m,
                            Price = 7991m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 3,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 12,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "honda 0",
                            OldPrice = 8530m,
                            Price = 7349m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 11,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 12,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "honda 1",
                            OldPrice = 4808m,
                            Price = 9742m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 19,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 12,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "honda 2",
                            OldPrice = 7014m,
                            Price = 9214m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 27,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 12,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "honda 3",
                            OldPrice = 4762m,
                            Price = 7007m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 35,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 12,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "honda 4",
                            OldPrice = 6939m,
                            Price = 5434m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 43,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 12,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "honda 5",
                            OldPrice = 8675m,
                            Price = 7032m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 51,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 12,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "honda 6",
                            OldPrice = 8839m,
                            Price = 6648m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 59,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 12,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "honda 7",
                            OldPrice = 9289m,
                            Price = 6494m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 67,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 12,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "honda 8",
                            OldPrice = 5671m,
                            Price = 6750m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 75,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 12,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "honda 9",
                            OldPrice = 7491m,
                            Price = 5993m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 4,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 13,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "toyota 0",
                            OldPrice = 8530m,
                            Price = 9717m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 12,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 13,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "toyota 1",
                            OldPrice = 4808m,
                            Price = 9918m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 20,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 13,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "toyota 2",
                            OldPrice = 7014m,
                            Price = 9028m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 28,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 13,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "toyota 3",
                            OldPrice = 4762m,
                            Price = 7484m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 36,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 13,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "toyota 4",
                            OldPrice = 6939m,
                            Price = 5552m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 44,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 13,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "toyota 5",
                            OldPrice = 8675m,
                            Price = 9167m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 52,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 13,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "toyota 6",
                            OldPrice = 8839m,
                            Price = 7512m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 60,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 13,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "toyota 7",
                            OldPrice = 9289m,
                            Price = 5739m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 68,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 13,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "toyota 8",
                            OldPrice = 5671m,
                            Price = 9182m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 76,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 13,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "toyota 9",
                            OldPrice = 7491m,
                            Price = 5857m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 5,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 14,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "mercedes 0",
                            OldPrice = 8530m,
                            Price = 5357m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 13,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 14,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "mercedes 1",
                            OldPrice = 4808m,
                            Price = 8967m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 21,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 14,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "mercedes 2",
                            OldPrice = 7014m,
                            Price = 9760m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 29,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 14,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "mercedes 3",
                            OldPrice = 4762m,
                            Price = 6096m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 37,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 14,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "mercedes 4",
                            OldPrice = 6939m,
                            Price = 6014m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 45,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 14,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "mercedes 5",
                            OldPrice = 8675m,
                            Price = 6081m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 53,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 14,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "mercedes 6",
                            OldPrice = 8839m,
                            Price = 9172m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 61,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 14,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "mercedes 7",
                            OldPrice = 9289m,
                            Price = 7077m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 69,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 14,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "mercedes 8",
                            OldPrice = 5671m,
                            Price = 7223m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 77,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 14,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "mercedes 9",
                            OldPrice = 7491m,
                            Price = 5929m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 6,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 23,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "lexus 0",
                            OldPrice = 8530m,
                            Price = 8885m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 14,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 23,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "lexus 1",
                            OldPrice = 4808m,
                            Price = 7029m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 22,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 23,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "lexus 2",
                            OldPrice = 7014m,
                            Price = 5079m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 30,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 23,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "lexus 3",
                            OldPrice = 4762m,
                            Price = 9959m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 38,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 23,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "lexus 4",
                            OldPrice = 6939m,
                            Price = 8257m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 46,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 23,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "lexus 5",
                            OldPrice = 8675m,
                            Price = 8694m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 54,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 23,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "lexus 6",
                            OldPrice = 8839m,
                            Price = 7349m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 62,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 23,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "lexus 7",
                            OldPrice = 9289m,
                            Price = 5178m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 70,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 23,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "lexus 8",
                            OldPrice = 5671m,
                            Price = 8586m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 78,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 23,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "lexus 9",
                            OldPrice = 7491m,
                            Price = 6485m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 7,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 24,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "maybach 0",
                            OldPrice = 8530m,
                            Price = 9655m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 15,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 24,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "maybach 1",
                            OldPrice = 4808m,
                            Price = 8762m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 23,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 24,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "maybach 2",
                            OldPrice = 7014m,
                            Price = 7698m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 31,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 24,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "maybach 3",
                            OldPrice = 4762m,
                            Price = 9445m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 39,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 24,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "maybach 4",
                            OldPrice = 6939m,
                            Price = 6358m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 47,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 24,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "maybach 5",
                            OldPrice = 8675m,
                            Price = 6376m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 55,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 24,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "maybach 6",
                            OldPrice = 8839m,
                            Price = 6236m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 63,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 24,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "maybach 7",
                            OldPrice = 9289m,
                            Price = 9912m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 71,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 24,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "maybach 8",
                            OldPrice = 5671m,
                            Price = 8096m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 79,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 24,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "maybach 9",
                            OldPrice = 7491m,
                            Price = 5417m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 8,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 25,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "benz 0",
                            OldPrice = 8530m,
                            Price = 7271m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 16,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 25,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "benz 1",
                            OldPrice = 4808m,
                            Price = 5009m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 24,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 25,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "benz 2",
                            OldPrice = 7014m,
                            Price = 8909m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 32,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 25,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "benz 3",
                            OldPrice = 4762m,
                            Price = 6859m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 40,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 25,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "benz 4",
                            OldPrice = 6939m,
                            Price = 8064m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 48,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 25,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "benz 5",
                            OldPrice = 8675m,
                            Price = 8845m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 56,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 25,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "benz 6",
                            OldPrice = 8839m,
                            Price = 6284m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 64,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 25,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "benz 7",
                            OldPrice = 9289m,
                            Price = 8115m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 72,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 25,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "benz 8",
                            OldPrice = 5671m,
                            Price = 5156m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 80,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 25,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "benz 9",
                            OldPrice = 7491m,
                            Price = 5904m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 9,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 26,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "amg 0",
                            OldPrice = 8530m,
                            Price = 7951m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 17,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 26,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "amg 1",
                            OldPrice = 4808m,
                            Price = 8968m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 25,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 26,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "amg 2",
                            OldPrice = 7014m,
                            Price = 7209m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 33,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 26,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "amg 3",
                            OldPrice = 4762m,
                            Price = 5889m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 41,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 26,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "amg 4",
                            OldPrice = 6939m,
                            Price = 7175m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 49,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 26,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "amg 5",
                            OldPrice = 8675m,
                            Price = 7504m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 57,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 26,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "amg 6",
                            OldPrice = 8839m,
                            Price = 6055m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 65,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 26,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "amg 7",
                            OldPrice = 9289m,
                            Price = 8190m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 73,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 26,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "amg 8",
                            OldPrice = 5671m,
                            Price = 9977m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 81,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 26,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "amg 9",
                            OldPrice = 7491m,
                            Price = 9437m,
                            Rate = 2
                        });
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Category", b =>
                {
                    b.HasOne("e_shop_backend_esense.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Product", b =>
                {
                    b.HasOne("e_shop_backend_esense.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Review", b =>
                {
                    b.HasOne("e_shop_backend_esense.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
