// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_shop_backend_esense.Data;

#nullable disable

namespace e_shop_backend_esense.Migrations
{
    [DbContext(typeof(EShopDbContext))]
    [Migration("20230207070938_uodate_newdb")]
    partial class uodate_newdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("e_shop_backend_esense.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cars"
                        },
                        new
                        {
                            Id = 11,
                            Name = "BMW",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Honda",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Toyouta",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 14,
                            Name = "Mercedes",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 23,
                            Name = "Lexus",
                            ParentCategoryId = 13
                        },
                        new
                        {
                            Id = 24,
                            Name = "Maybach",
                            ParentCategoryId = 14
                        },
                        new
                        {
                            Id = 25,
                            Name = "Benz",
                            ParentCategoryId = 14
                        },
                        new
                        {
                            Id = 26,
                            Name = "AMG",
                            ParentCategoryId = 14
                        },
                        new
                        {
                            Id = 2,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Laptops",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 17,
                            Name = "Monitors",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 16,
                            Name = "PC",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 27,
                            Name = "HP",
                            ParentCategoryId = 15
                        },
                        new
                        {
                            Id = 28,
                            Name = "Acer",
                            ParentCategoryId = 15
                        },
                        new
                        {
                            Id = 29,
                            Name = "Dell",
                            ParentCategoryId = 15
                        },
                        new
                        {
                            Id = 30,
                            Name = "LG",
                            ParentCategoryId = 17
                        },
                        new
                        {
                            Id = 31,
                            Name = "Samsung",
                            ParentCategoryId = 17
                        });
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStuck")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Rate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 11,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "BMW 0",
                            OldPrice = 50m,
                            Price = 296m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 10,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 11,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "BMW 1",
                            OldPrice = 50m,
                            Price = 407m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 18,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 11,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "BMW 2",
                            OldPrice = 50m,
                            Price = 208m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 3,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 12,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "honda 0",
                            OldPrice = 500m,
                            Price = 209m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 11,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 12,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "honda 1",
                            OldPrice = 500m,
                            Price = 275m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 19,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 12,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "honda 2",
                            OldPrice = 500m,
                            Price = 297m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 4,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 13,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "toyota 0",
                            OldPrice = 500m,
                            Price = 478m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 12,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 13,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "toyota 1",
                            OldPrice = 500m,
                            Price = 492m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 20,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 13,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "toyota 2",
                            OldPrice = 500m,
                            Price = 389m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 5,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 14,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "mercedes 0",
                            OldPrice = 500m,
                            Price = 354m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 13,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 14,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "mercedes 1",
                            OldPrice = 500m,
                            Price = 67m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 21,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 14,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "mercedes 2",
                            OldPrice = 500m,
                            Price = 437m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 6,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 23,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "lexus 0",
                            OldPrice = 500m,
                            Price = 264m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 14,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 23,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "lexus 1",
                            OldPrice = 500m,
                            Price = 181m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 22,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 23,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "lexus 2",
                            OldPrice = 500m,
                            Price = 55m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 7,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 24,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "maybach 0",
                            OldPrice = 500m,
                            Price = 295m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 15,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 24,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "maybach 1",
                            OldPrice = 500m,
                            Price = 190m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 23,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 24,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "maybach 2",
                            OldPrice = 500m,
                            Price = 91m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 8,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 25,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "benz 0",
                            OldPrice = 500m,
                            Price = 459m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 16,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 25,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "benz 1",
                            OldPrice = 500m,
                            Price = 260m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 24,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 25,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "benz 2",
                            OldPrice = 500m,
                            Price = 379m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 9,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 26,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "amg 0",
                            OldPrice = 500m,
                            Price = 483m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 17,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 26,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "amg 1",
                            OldPrice = 500m,
                            Price = 279m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 25,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 26,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "amg 2",
                            OldPrice = 500m,
                            Price = 119m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 91,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 15,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "laptops 0",
                            OldPrice = 500m,
                            Price = 129m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 99,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 15,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "laptops 1",
                            OldPrice = 500m,
                            Price = 469m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 107,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 15,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "laptops 2",
                            OldPrice = 500m,
                            Price = 408m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 92,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 16,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "pc 0",
                            OldPrice = 500m,
                            Price = 107m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 100,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 16,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "pc 1",
                            OldPrice = 500m,
                            Price = 174m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 108,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 16,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "pc 2",
                            OldPrice = 500m,
                            Price = 270m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 95,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 27,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "hp 0",
                            OldPrice = 400m,
                            Price = 434m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 103,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 27,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "hp 1",
                            OldPrice = 400m,
                            Price = 394m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 111,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 27,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "hp 2",
                            OldPrice = 400m,
                            Price = 203m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 94,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 29,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "dell 0",
                            OldPrice = 250m,
                            Price = 108m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 102,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 29,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "dell 1",
                            OldPrice = 250m,
                            Price = 169m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 110,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 29,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "dell 2",
                            OldPrice = 250m,
                            Price = 226m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 96,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 28,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "maybach 0",
                            OldPrice = 100m,
                            Price = 487m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 104,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 28,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "maybach 1",
                            OldPrice = 100m,
                            Price = 223m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 112,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 28,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "maybach 2",
                            OldPrice = 100m,
                            Price = 291m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 97,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 30,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "lg 0",
                            OldPrice = 1500m,
                            Price = 256m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 105,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 30,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "lg 1",
                            OldPrice = 1500m,
                            Price = 60m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 113,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 30,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "lg 2",
                            OldPrice = 1500m,
                            Price = 250m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 98,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 31,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "samsung 0",
                            OldPrice = 1000m,
                            Price = 154m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 106,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 31,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "samsung 1",
                            OldPrice = 1000m,
                            Price = 289m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 114,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 31,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "samsung 2",
                            OldPrice = 1000m,
                            Price = 309m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 93,
                            AdditionalInfo = "{}",
                            Available = false,
                            CategoryId = 17,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = false,
                            Name = "monitors 0",
                            OldPrice = 200m,
                            Price = 453m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 101,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 17,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "monitors 1",
                            OldPrice = 200m,
                            Price = 359m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 109,
                            AdditionalInfo = "{}",
                            Available = true,
                            CategoryId = 17,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageURL = "https://via.placeholder.com/600x800",
                            InStuck = true,
                            Name = "monitors 2",
                            OldPrice = 200m,
                            Price = 487m,
                            Rate = 4
                        });
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Category", b =>
                {
                    b.HasOne("e_shop_backend_esense.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Product", b =>
                {
                    b.HasOne("e_shop_backend_esense.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Review", b =>
                {
                    b.HasOne("e_shop_backend_esense.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
