// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using e_shop_backend_esense.Data;

#nullable disable

namespace e_shop_backend_esense.Migrations
{
    [DbContext(typeof(EShopDbContext))]
    partial class EShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("e_shop_backend_esense.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cars"
                        },
                        new
                        {
                            Id = 11,
                            Name = "BMW",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Honda",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Toyouta",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 14,
                            Name = "Mercedes",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 23,
                            Name = "Lexus",
                            ParentCategoryId = 13
                        },
                        new
                        {
                            Id = 24,
                            Name = "Maybach",
                            ParentCategoryId = 14
                        },
                        new
                        {
                            Id = 25,
                            Name = "Benz",
                            ParentCategoryId = 14
                        },
                        new
                        {
                            Id = 26,
                            Name = "AMG",
                            ParentCategoryId = 14
                        },
                        new
                        {
                            Id = 2,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Laptops",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 17,
                            Name = "Monitors",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 16,
                            Name = "PC",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 27,
                            Name = "HP",
                            ParentCategoryId = 15
                        },
                        new
                        {
                            Id = 28,
                            Name = "Acer",
                            ParentCategoryId = 15
                        },
                        new
                        {
                            Id = 29,
                            Name = "Dell",
                            ParentCategoryId = 15
                        },
                        new
                        {
                            Id = 30,
                            Name = "LG",
                            ParentCategoryId = 17
                        },
                        new
                        {
                            Id = 31,
                            Name = "Samsung",
                            ParentCategoryId = 17
                        });
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Rate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            AdditionalInfo = "{}",
                            CategoryId = 11,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = true,
                            IsInStock = false,
                            Name = "BMW 0",
                            OldPrice = 50m,
                            Price = 304m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 10,
                            AdditionalInfo = "{}",
                            CategoryId = 11,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = true,
                            IsInStock = false,
                            Name = "BMW 1",
                            OldPrice = 50m,
                            Price = 413m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 18,
                            AdditionalInfo = "{}",
                            CategoryId = 11,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = false,
                            Name = "BMW 2",
                            OldPrice = 50m,
                            Price = 286m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 3,
                            AdditionalInfo = "{}",
                            CategoryId = 12,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = true,
                            Name = "honda 0",
                            OldPrice = 500m,
                            Price = 127m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 11,
                            AdditionalInfo = "{}",
                            CategoryId = 12,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = false,
                            Name = "honda 1",
                            OldPrice = 500m,
                            Price = 379m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 19,
                            AdditionalInfo = "{}",
                            CategoryId = 12,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = false,
                            Name = "honda 2",
                            OldPrice = 500m,
                            Price = 253m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 4,
                            AdditionalInfo = "{}",
                            CategoryId = 13,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = false,
                            Name = "toyota 0",
                            OldPrice = 500m,
                            Price = 334m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 12,
                            AdditionalInfo = "{}",
                            CategoryId = 13,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = true,
                            IsInStock = false,
                            Name = "toyota 1",
                            OldPrice = 500m,
                            Price = 216m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 20,
                            AdditionalInfo = "{}",
                            CategoryId = 13,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = false,
                            Name = "toyota 2",
                            OldPrice = 500m,
                            Price = 213m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 5,
                            AdditionalInfo = "{}",
                            CategoryId = 14,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = true,
                            IsInStock = false,
                            Name = "mercedes 0",
                            OldPrice = 500m,
                            Price = 318m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 13,
                            AdditionalInfo = "{}",
                            CategoryId = 14,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = true,
                            Name = "mercedes 1",
                            OldPrice = 500m,
                            Price = 236m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 21,
                            AdditionalInfo = "{}",
                            CategoryId = 14,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = false,
                            Name = "mercedes 2",
                            OldPrice = 500m,
                            Price = 267m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 6,
                            AdditionalInfo = "{}",
                            CategoryId = 23,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = false,
                            Name = "lexus 0",
                            OldPrice = 500m,
                            Price = 279m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 14,
                            AdditionalInfo = "{}",
                            CategoryId = 23,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = true,
                            IsInStock = true,
                            Name = "lexus 1",
                            OldPrice = 500m,
                            Price = 452m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 22,
                            AdditionalInfo = "{}",
                            CategoryId = 23,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = true,
                            Name = "lexus 2",
                            OldPrice = 500m,
                            Price = 80m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 7,
                            AdditionalInfo = "{}",
                            CategoryId = 24,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = false,
                            Name = "maybach 0",
                            OldPrice = 500m,
                            Price = 255m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 15,
                            AdditionalInfo = "{}",
                            CategoryId = 24,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = false,
                            Name = "maybach 1",
                            OldPrice = 500m,
                            Price = 253m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 23,
                            AdditionalInfo = "{}",
                            CategoryId = 24,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = false,
                            Name = "maybach 2",
                            OldPrice = 500m,
                            Price = 75m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 8,
                            AdditionalInfo = "{}",
                            CategoryId = 25,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = true,
                            Name = "benz 0",
                            OldPrice = 500m,
                            Price = 142m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 16,
                            AdditionalInfo = "{}",
                            CategoryId = 25,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = true,
                            IsInStock = false,
                            Name = "benz 1",
                            OldPrice = 500m,
                            Price = 289m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 24,
                            AdditionalInfo = "{}",
                            CategoryId = 25,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = false,
                            Name = "benz 2",
                            OldPrice = 500m,
                            Price = 379m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 9,
                            AdditionalInfo = "{}",
                            CategoryId = 26,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = true,
                            Name = "amg 0",
                            OldPrice = 500m,
                            Price = 452m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 17,
                            AdditionalInfo = "{}",
                            CategoryId = 26,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = true,
                            Name = "amg 1",
                            OldPrice = 500m,
                            Price = 233m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 25,
                            AdditionalInfo = "{}",
                            CategoryId = 26,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = true,
                            IsInStock = true,
                            Name = "amg 2",
                            OldPrice = 500m,
                            Price = 309m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 91,
                            AdditionalInfo = "{}",
                            CategoryId = 15,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = false,
                            Name = "laptops 0",
                            OldPrice = 500m,
                            Price = 201m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 99,
                            AdditionalInfo = "{}",
                            CategoryId = 15,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = true,
                            IsInStock = false,
                            Name = "laptops 1",
                            OldPrice = 500m,
                            Price = 296m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 107,
                            AdditionalInfo = "{}",
                            CategoryId = 15,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = true,
                            Name = "laptops 2",
                            OldPrice = 500m,
                            Price = 317m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 92,
                            AdditionalInfo = "{}",
                            CategoryId = 16,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = true,
                            IsInStock = false,
                            Name = "pc 0",
                            OldPrice = 500m,
                            Price = 322m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 100,
                            AdditionalInfo = "{}",
                            CategoryId = 16,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = true,
                            Name = "pc 1",
                            OldPrice = 500m,
                            Price = 168m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 108,
                            AdditionalInfo = "{}",
                            CategoryId = 16,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = true,
                            IsInStock = false,
                            Name = "pc 2",
                            OldPrice = 500m,
                            Price = 447m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 95,
                            AdditionalInfo = "{}",
                            CategoryId = 27,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = true,
                            Name = "hp 0",
                            OldPrice = 400m,
                            Price = 227m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 103,
                            AdditionalInfo = "{}",
                            CategoryId = 27,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = true,
                            IsInStock = false,
                            Name = "hp 1",
                            OldPrice = 400m,
                            Price = 159m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 111,
                            AdditionalInfo = "{}",
                            CategoryId = 27,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = false,
                            Name = "hp 2",
                            OldPrice = 400m,
                            Price = 59m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 94,
                            AdditionalInfo = "{}",
                            CategoryId = 29,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = true,
                            IsInStock = true,
                            Name = "dell 0",
                            OldPrice = 250m,
                            Price = 295m,
                            Rate = 4
                        },
                        new
                        {
                            Id = 102,
                            AdditionalInfo = "{}",
                            CategoryId = 29,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = true,
                            IsInStock = false,
                            Name = "dell 1",
                            OldPrice = 250m,
                            Price = 177m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 110,
                            AdditionalInfo = "{}",
                            CategoryId = 29,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = false,
                            Name = "dell 2",
                            OldPrice = 250m,
                            Price = 493m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 96,
                            AdditionalInfo = "{}",
                            CategoryId = 28,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = true,
                            Name = "acer 0",
                            OldPrice = 100m,
                            Price = 242m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 104,
                            AdditionalInfo = "{}",
                            CategoryId = 28,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = false,
                            Name = "acer 1",
                            OldPrice = 100m,
                            Price = 181m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 112,
                            AdditionalInfo = "{}",
                            CategoryId = 28,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = true,
                            IsInStock = false,
                            Name = "acer 2",
                            OldPrice = 100m,
                            Price = 323m,
                            Rate = 2
                        },
                        new
                        {
                            Id = 97,
                            AdditionalInfo = "{}",
                            CategoryId = 30,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = true,
                            Name = "lg 0",
                            OldPrice = 1500m,
                            Price = 74m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 105,
                            AdditionalInfo = "{}",
                            CategoryId = 30,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = false,
                            Name = "lg 1",
                            OldPrice = 1500m,
                            Price = 450m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 113,
                            AdditionalInfo = "{}",
                            CategoryId = 30,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = true,
                            Name = "lg 2",
                            OldPrice = 1500m,
                            Price = 277m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 98,
                            AdditionalInfo = "{}",
                            CategoryId = 31,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = true,
                            IsInStock = true,
                            Name = "samsung 0",
                            OldPrice = 1000m,
                            Price = 99m,
                            Rate = 1
                        },
                        new
                        {
                            Id = 106,
                            AdditionalInfo = "{}",
                            CategoryId = 31,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = true,
                            IsInStock = true,
                            Name = "samsung 1",
                            OldPrice = 1000m,
                            Price = 316m,
                            Rate = 5
                        },
                        new
                        {
                            Id = 114,
                            AdditionalInfo = "{}",
                            CategoryId = 31,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = true,
                            IsInStock = true,
                            Name = "samsung 2",
                            OldPrice = 1000m,
                            Price = 491m,
                            Rate = 3
                        },
                        new
                        {
                            Id = 93,
                            AdditionalInfo = "{}",
                            CategoryId = 17,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = true,
                            IsInStock = false,
                            Name = "monitors 0",
                            OldPrice = 200m,
                            Price = 333m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 101,
                            AdditionalInfo = "{}",
                            CategoryId = 17,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = true,
                            IsInStock = false,
                            Name = "monitors 1",
                            OldPrice = 200m,
                            Price = 218m,
                            Rate = 0
                        },
                        new
                        {
                            Id = 109,
                            AdditionalInfo = "{}",
                            CategoryId = 17,
                            Description = "Lorem ipsum dolor ut sit ame dolore adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat Nostrud duis molestie at dolore.",
                            ImageUrl = "https://via.placeholder.com/600x800",
                            IsAvailable = false,
                            IsInStock = true,
                            Name = "monitors 2",
                            OldPrice = 200m,
                            Price = 283m,
                            Rate = 4
                        });
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Category", b =>
                {
                    b.HasOne("e_shop_backend_esense.Models.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Product", b =>
                {
                    b.HasOne("e_shop_backend_esense.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Review", b =>
                {
                    b.HasOne("e_shop_backend_esense.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("e_shop_backend_esense.Models.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
